version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- cmd: dotnet restore src/Vlingo.Wire.sln
build:
  project: src/Vlingo.Wire.sln
  verbosity: minimal
  publish_nuget: true
test_script:
- cmd: dotnet test src/Vlingo.Wire.Tests
deploy:
- provider: NuGet
  api_key:
    secure: oy2ax2ob7rl7zlnd3nmayjzntccpzvmu7ahxy4wtlq74jy
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master